version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "io.github.bonigarcia:webdrivermanager"
      - dependency-name: "*"
        update-types: [ "version-update:semver-patch" ]
