logging.level:
  org.apache.pdfbox.io.ScratchFileBuffer: WARN

flows.runner:
  cron: "0 0/30 * * * ?"

kaufland:
  base.url: https://www.kaufland.bg/aktualni-predlozheniya/ot-ponedelnik.html

lidl:
  base.url: https://www.lidl.bg

fantastico:
  url: https://www.fantastico.bg/special-offers

billa:
  url: https://ssbbilla.site/weekly

tmarket:
  base.url: https://tmarketonline.bg/

google:
  custom.search:
    url: https://www.googleapis.com/customsearch/v1?key=${GOOGLE_API_KEY:}&cx=0b1305ac3733516ec&searchType=image

spring:
  jpa:
    hibernate.ddl-auto: none
  datasource:
    hikari:
      maximum-pool-size: 2
    url: "jdbc:postgresql://queenie.db.elephantsql.com:5432/nwshtxej"
    username: ${DB_USERNAME:}
    password: ${DB_PASSWORD:}