api:
  server.url: https://sofia-supermarkets-api-proxy.stefan-bratanov.workers.dev

server:
  compression.enabled: true

logging:
  file:
    name: ${java.io.tmpdir}/${spring.application.name}.log
    max-size: 50MB
  level:
    org.apache.pdfbox.io.ScratchFileBuffer: WARN

management:
  endpoints:
    web.exposure.include: "*"

flows.runner:
  cron: "0 0/30 * * * ?"

alcohol.retriever:
  cron: "0 0/10 * * * ?"

image.verifier:
  cron: "0 0/10 * * * ?"

kaufland:
  base.url: https://www.kaufland.bg/aktualni-predlozheniya/oferti.html

lidl:
  base.url: https://www.lidl.bg

fantastico:
  url: https://www.fantastico.bg/special-offers

billa:
  url: https://ssbbilla.site

tmarket:
  base.url: https://tmarketonline.bg/

google:
  image.search:
    url: https://www.google.bg/search?source=lnms&tbm=isch
  custom.search:
    url: https://www.googleapis.com/customsearch/v1?key=AIzaSyCFhQUZcq9m-WfDhTmXIbJwZ2nkzT5zwTI&cx=0b1305ac3733516ec&searchType=image

cloudinary:
  cloud.name: dvhremyag
  api:
    key: 692784477265895
    secret: _w1wW_guBtn64JGpY6qA7thz864

spring:
  application.name: sofia-supermarkets-api
  jpa:
    hibernate.ddl-auto: update
  datasource:
    hikari:
      maximum-pool-size: 2
    url: jdbc:postgresql://localhost:5471/brochures_db
    username: brochures
    password: password
    driver-class-name: org.postgresql.Driver
  jackson:
    serialization:
      write-dates-as-timestamps: false

springdoc:
  swagger-ui:
    tagsSorter: alpha
    docExpansion: none